CREATE OR REPLACE STORAGE INTEGRATION powerbi_3_integration
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN =
'arn:aws:iam::<AWS_ACCOUNT_ID>:role/powerbi-role'
STORAGE_ALLOWED_LOCATIONS =
('s3://your-loan-data-bucket');

DESC INTEGRATION powerbi_3_integration;